### ISSUE TITLE
Document debouncePeriod

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-replication-scheduler#13]

**Comment by staltz** [comment]
This is an internal config, exposed in the ssb config object just to make it easier for tests, so we don't need a README documentation, but if you want, you can add some code comments. It basically controls how often will we trigger `ssb.ebt.request()` calls. We trigger those when the `requestManager.add()` has "calmed down", i.e. after `debouncePeriod` milliseconds have passed in which `add()` was **not** called.

**Comment by staltz** [comment]
A timeline of what debounce looks like, assuming 100ms of debouncePeriod:

```
                   |---100ms---|
-----o-----o---o---o----------------->

-------------------------------o----->
```

**Comment by Powersource** [comment]
documented in 8abaeee4311a74b6592e25171854a9f15e77483d now
